### ISSUE TITLE
Missing data point?

### ISSUE THREAD

**Issue by thiagoarrais** [hasharray/jsperf#62]
Maybe I'm interpreting it wrong, but I've rendered the site locally and datapoint [03b12a4c-9c64-4f6f-9e09-378890f3c769](https://github.com/hasharray/jsperf/blob/master/_data/for-vs-foreach-vs-yolo/03b12a4c-9c64-4f6f-9e09-378890f3c769.yml) isn't presented anywhere in http://localhost:4000/for-vs-foreach-vs-yolo (sorry for the localhost URL. is this online somewhere?). It is a Chrome 53 datapoint and the report only shows Chrome versions 54 and 55.

(By the way, found this while working on [jekyll#5513](https://github.com/jekyll/jekyll/pull/5513).)

**Comment by caspervonb** [comment]
Only the latest 2 major versions are shown (https://github.com/hasharray/jsperf/blob/master/_layouts/benchmark.html#L67) 😉

**Comment by thiagoarrais** [comment]
Awesome! I'm planning to use jsperf as a test case for my PR. That info will be very useful.
